version: "3"

services:
  api:
    image: donnieashok/api
    build:
      context: api/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    ports:
    - 8080:8080/tcp
    volumes:
      - ./api:/build

  addition:
    image: donnieashok/addition
    build:
      context: addition/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    ports:
    - 8081:8080/tcp
    volumes:
      - ./addition:/build

  subtraction:
    image: donnieashok/subtraction
    build:
      context: subtraction/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    ports:
    - 8082:8080/tcp
    volumes:
      - ./subtraction:/build

  multiplication:
    image: donnieashok/multiplication
    build:
      context: multiplication/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    ports:
    - 8083:8080/tcp
    volumes:
      - ./multiplication:/build

  division:
    image: donnieashok/division
    build:
      context: division/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    ports:
    - 8084:8080/tcp
    volumes:
      - ./division:/build
