#!/usr/bin/env -S docker-compose -p kube-ms -f

version: "3.8"

networks:
  default:
    internal: false
    external: false
    attachable: true

services:
  gateway:
    image: traefik:latest
    command:
    - --accesslog=true
    - --api.insecure=true
    - --api.dashboard=true
    - --providers.docker.endpoint=unix:///var/run/docker.sock
    - --providers.docker.defaultRule=PathPrefix(`/{{ .Name }}`)
    - --providers.docker.exposedByDefault=true
    - --entrypoints.web.address=:80
    - --entrypoints.web.http.middlewares=strip@docker
    networks:
    - default
    ports:
    - 8000:8080/tcp
    - 8085:80/tcp
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
    - traefik.http.middlewares.strip.stripprefixregex.regex=/[a-z0-9-]+

  api:
    build:
      context: api/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    networks:
    - default
    ports:
    - 8080/tcp
    labels:
      traefik.enable: "true"
    volumes:
      - ./api:/build
  
  addition:
    build:
      context: addition/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    networks:
    - default
    ports:
    - 8081:8080/tcp
    volumes:
      - ./addition:/build

  subtraction:
    build:
      context: subtraction/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    networks:
    - default
    ports:
    - 8082:8080/tcp
    volumes:
      - ./subtraction:/build

  multiplication:
    build:
      context: multiplication/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    networks:
    - default
    ports:
    - 8083:8080/tcp
    volumes:
      - ./multiplication:/build

  division:
    build:
      context: division/
      dockerfile: ../Dockerfile.dev
    command: goreload .
    networks:
    - default
    ports:
    - 8084:8080/tcp
    volumes:
      - ./division:/build
