apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
    a3ViZUNBMB4XDTIyMDcyOTE1MzUyMloXDTMyMDcyNzE1MzUyMlowFTETMBEGA1UE
    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKgj
    mfd9r+mwBjA2RtYELx9O12/dO/8TcHQTn9HdtdCoiEfLP710gfMRpXgH8PzJhy6W
    nNPGc4Eh82ph2OLI5V259dCQmujlw2temum43DjdNjBIiwzPolalWmEf+PoGxUPK
    toUWh3ncMGDK7AtQn3PEZC/tjcZHYH7LN2KWCLjuMym2GS7pdnBKEo+h+kTFJfsn
    4MAh+BRa5JTFN2zhysRW2D89NndSgGrz4BenHWzaNQ9ycEJfHKYEcvi/icCUyYaZ
    WF5OkYjhbO9mfEgoA8HvFqPFz3QoMbCdZOaSiCgssZsv8AonCtETpKknZs6WgJYv
    vV83MohPk1FMKi2CA78CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
    BBRkpc6Kkl1SwSlnPaA5COBmEG/2oTANBgkqhkiG9w0BAQsFAAOCAQEAfId1wwtZ
    zu01ITeWSiodq/lTV8Kw0NQfIOi3C1IVmX2jkP1T/HFkImAeHHq2OeObYRhr3Bwr
    CD110ed+D9TjZD7V4JeJOY2MtisbnxPceMHj73/+q+bLJrsf5uva4ylf07a5UjJV
    R1s7bLmnrx8bzuXfQ3tWAx1OzV1L4/GSN1QmOxUXUZY9DJqngDxY7wCVR6mz7KOx
    7S9Q63rJ2bHX6WVVDI1sLHAUUddOPfupuYkxmdWWEn4S1EOANPYYuDN8bfFZz0VZ
    O0gfwDu8WIzCnSBn7Fy1+qCo5cvrcB3qKO3GGAnTUHsGfAXHMqCJ3LQ8dLgk76Cd
    TsOT7K2okUh5OQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2022-07-30T15:36:00Z"
  name: kube-root-ca.crt
  namespace: default
  resourceVersion: "345"
  uid: 8f9af555-a12d-4b5f-b34e-a8aad8e61193
