apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-07-30T16:08:04Z"
  generation: 1
  labels:
    app: addition
  name: addition
  namespace: default
  resourceVersion: "1819"
  uid: 6c29d358-d6a9-4784-b155-fe4ceb19c9d4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: addition
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: addition
    spec:
      containers:
      - image: donnieashok/addition:prod
        imagePullPolicy: IfNotPresent
        name: addition
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-30T16:08:07Z"
    lastUpdateTime: "2022-07-30T16:08:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-07-30T16:08:04Z"
    lastUpdateTime: "2022-07-30T16:08:07Z"
    message: ReplicaSet "addition-6f8fd4f9b9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
