apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: calculator
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.148.138
  clusterIPs:
  - 10.100.148.138
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31258
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  sessionAffinity: None
  type: LoadBalancer
