apiVersion: v1
kind: Service
metadata:
  labels:
    app: addition
  name: addition
  namespace: calculator
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.135.128
  clusterIPs:
  - 10.101.135.128
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31504
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: addition
  sessionAffinity: None
  type: LoadBalancer
