applications:
  - image: donnieashok/addition:prod
    name: addition
    nodePort: 30010
  - image: donnieashok/api:prod
    name: api
    nodePort: 30020
  - image: donnieashok/division:prod
    name: division
    nodePort: 30030
  - image: donnieashok/multiplication:prod
    name: multiplication
    nodePort: 30040
  - image: donnieashok/subtraction:prod
    name: subtraction
    nodePort: 30050
